import './styles.scss';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Roboto } from 'next/font/google';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import { CssBaseline, InitColorSchemeScript } from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import { theme } from '@/theme';
import { ThemeConfigProvider } from '@/contexts/uiConfigContext';
import { NotificationProvider } from '@/contexts/notificationContext';

const roboto = Roboto({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={roboto.variable} suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute='class' />
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <ThemeConfigProvider>
              <CssBaseline />
              <NotificationProvider>{children}</NotificationProvider>
            </ThemeConfigProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
